### ISSUE TITLE
请问有9g servo版本的那只狗狗的图纸源文件吗？

### ISSUE THREAD

**Issue by hyansuper** [YANGGTT/servo-dogbot#3]
我基于ROS写了个T站的那只狗狗的仿真，github.com/hyansuper/spotmicro，实现了两种步态，主要思路是根据速度指令预测下一个落脚点然后抬起一只脚，同时根据步子的节奏移动重心到另外三只支撑脚构成的平面内。步子看起来还算自然。其他形式的步态有空还会研究。
我还没打印实体机器人，我也担心996 servo扭矩不足。

你的9g servo版本的小狗看起来会更灵活，不知你有没有它活动的视屏可分享，另外，我想将我的spotmicro项目用于这个9g servo版本的小狗，你是否愿意分享设计源文件呢（Solidworks 或 Fusion360的格式）这样如果我需要修改尺寸会更方便。谢谢！

**Comment by wuyangning** [comment]
第一个文件夹里的puppy-bot.STEP就是设计源文件。这个我还没动起来，没时间做了。腿是5杆机构，处理起来可能比较麻烦。

**Comment by hyansuper** [comment]
你用的是塑料齿轮的蓝色舵机吗？请问舵机转子和连杆打印件怎么固定在一起？
